---
title: Sexual dimorphism in Chinstrap penguins"
author: "Benedikt Haarscheidt, Jaesub Kim, Ahmed Tijani Akinfalabi "
date: "`r Sys.Date()`"
output:
  html_document:
    toc: yes
    toc_depth: 5
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '5'
---
```{r echo=FALSE, include=FALSE}

library(palmerpenguins)
library(datasets)
library(MASS)

library(DAAG)
library(palmerpenguins)
```



This is the mammals dataset containing body and brain weigth of 62 land species
```{r}
data(mammals)
head(mammals)


```
This is the possum datase containing measurments of possums in australia 
```{r}
data(possum)
head(possum)
```

## Data preparation

Subsetting the penguin species 
```{r}
head(penguins)
df=penguins
adelieset <- df[df$species == "Adelie", ]
adeliemale =adelieset[adelieset$sex == "male",]
adeliefemale = adelieset[adelieset$sex =="female",]
gentooset=df[df$species =="Gentoo",]
gentoomale = gentooset[gentooset$sex =="male",]
gentoofemale = gentooset[gentooset$sex =="female",]

chinstrapset=df[df$species =="Chinstrap",]
chinstrapmale=chinstrapset[chinstrapset$sex =="male",]
chinstrapfemale=chinstrapset[chinstrapset$sex =="female",]

```


```{r}
sextable=table(penguins$sex,penguins$species)
sextable
adeliesex=sextable[,1]
gentoosex=sextable[,3]
chinstrapsex=sextable[,2]

```



# Adelie
## Data analysis
numerical data summary adelie:
```{r}
#Important to take arithmetic mean 
meanbodymassadelie=mean(adelieset$body_mass_g, na.rm=TRUE)
meanbodymassadeliemale=mean(adeliemale$body_mass_g, na.rm=TRUE)
meanbodymassadeliefemale=mean(adeliefemale$body_mass_g, na.rm=TRUE)
medianbodymassadeliemale=median(adeliemale$body_mass_g, na.rm=TRUE)
medianbodymassadeliefemale=median(adeliefemale$body_mass_g, na.rm=TRUE)

summaryadeliefemale=summary(adeliefemale[,3:6])
summaryadeliemale=summary(adeliemale[,3:6])


```

## Plots:

Stripcharts for all the attributes
```{r}
stripchart(adelieset$body_mass_g~adelieset$sex, main="Massdistribution between the biological sexes",method="stack", col=c(2,4))
stripchart(adelieset$bill_length_mm~adelieset$sex, main="Massdistribution between the biological sexes",method="stack", col=c(2,4))
stripchart(adelieset$flipper_length_mm~adelieset$sex, main="Massdistribution between the biological sexes",method="stack", col=c(2,4))
stripchart(adelieset$bill_depth_mm~adelieset$sex, main="Massdistribution between the biological sexes",method="stack", col=c(2,4))

```

```{r}

## Summary statistics
xy <- summary(adeliemale$body_mass_g)



# Create a histogram
hist(adeliemale$body_mass_g,
     main = "Histogram of Body Mass of Male Adelie Penguins",
     xlab = "Body Mass Distribution in gram",
     ylab = "Density",
     col = "lightblue",
     mar = c(2, 1, 2, 1),
     oma = c(2, 1, 2, 1),
   
     freq = FALSE, # Using density instead of frequency
      # Set x-axis limits to cover full data range
     )     # Do not plot x-axis yet


# Add density line
lines(density(adeliemale$body_mass_g, na.rm = TRUE), col = "blue", lwd = 2)

# Add mean and median lines
abline(v = meanbodymassadeliemale, col = "black", lwd = 2, lty = 2)
abline(v = medianbodymassadeliemale, col = "red", lwd = 2, lty = 2)
abline(v = meanbodymassadeliefemale, col = "black", lwd = 2, lty = 1)
abline(v = medianbodymassadeliefemale, col = "red", lwd = 2, lty = 1)

# Add legend
legend("topright", legend = c("Density", "Mean male", "Median male", "Mean female", "Median female"), 
       col = c("blue", "black", "red", "black", "red"), lty = c(1, 2, 2, 1, 1), lwd = 2,cex=0.8)


```

```{r}
hist(adeliemale$body_mass_g,
     main="Histogram of Body Mass of Male Adelie Penguins",
     )
```












# chinstrap

## Datasummary numerical
```{r}
meanbodychinstrapmale=mean(adelieset$body_mass_g, na.rm=TRUE)
meanbodychinstrapfemale=mean(adeliemale$body_mass_g, na.rm=TRUE)
meanbodymassadeliefemale=mean(adeliefemale$body_mass_g, na.rm=TRUE)
medianbodymassadeliemale=median(adeliemale$body_mass_g, na.rm=TRUE)
medianbodymassadeliefemale=median(adeliefemale$body_mass_g, na.rm=TRUE)

summaryadeliefemale=summary(adeliefemale[,3:6])
summaryadeliemale=summary(adeliemale[,3:6])

```

